### ISSUE TITLE
Struggling to compile with Go 1.13 and 1.14

### ISSUE THREAD

**Issue by toothbrush** [realestate-com-au/shush#22]
I apologise upfront if i'm being dense, because i'm not much of a Golang programmer.  I am on macOS 10.14.6 and used Homebrew to `brew install go` (gives me Golang 1.14), and when that didn't work, `brew install go@1.13`.

In both cases, running the recommended `go get github.com/realestate-com-au/shush` gives these errors:

```
# github.com/realestate-com-au/shush
go/src/github.com/realestate-com-au/shush/main.go:22:22: cannot use cli.StringSliceFlag literal (type cli.StringSliceFlag) as type cli.Flag in array or slice literal:
	cli.StringSliceFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/realestate-com-au/shush/main.go:25:4: unknown field 'EnvVar' in struct literal of type cli.StringSliceFlag
go/src/github.com/realestate-com-au/shush/main.go:27:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/realestate-com-au/shush/main.go:30:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/realestate-com-au/shush/main.go:39:17: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/realestate-com-au/shush/main.go:44:4: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
go/src/github.com/realestate-com-au/shush/main.go:45:11: invalid argument c.Args() (type cli.Args) for len
go/src/github.com/realestate-com-au/shush/main.go:57:7: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
go/src/github.com/realestate-com-au/shush/main.go:58:7: c.GlobalStringSlice undefined (type *cli.Context has no field or method GlobalStringSlice)
go/src/github.com/realestate-com-au/shush/main.go:63:46: cannot slice c.Args() (type cli.Args)
go/src/github.com/realestate-com-au/shush/main.go:44:4: too many errors
```

Am i doing something wrong?

**Comment by toothbrush** [comment]
Now i'm really confused.  Doing the following seems to work fine:

```shellsession
$ git clone git@github.com:realestate-com-au/shush.git
Cloning into 'shush'...
$ cd shush
$ make
..all goes well..
```

Why is the result of that different to `go get ...`?

**Comment by toothbrush** [comment]
Okay, this worked for me:

```
GO111MODULE=on go get -u github.com/realestate-com-au/shush
```

I should probably close this issue, i'm guessing my environment isn't sane.  I thought that Go>=1.13 should default to `GO111MODULE=on`? 😕
